services:
  - type: web
    name: my-saas-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: API_KEY
        value: {{ env.API_KEY }}
      - key: DATABASE_URL
        value: {{ env.DATABASE_URL }}
      - key: SECRET_KEY
        value: {{ env.SECRET_KEY }}
    repo: https://github.com/tuo_username/tuo_repository
