name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        channels: conda-forge
        activate-environment: nba_env  # Usa un ambiente dedicato

    - name: Create and activate Conda environment
      run: |
        conda create -n nba_env python=3.10 -y
        conda init bash
        echo "CONDA_BASE=$(conda info --base)" >> $GITHUB_ENV
        echo "source $CONDA_BASE/etc/profile.d/conda.sh" >> $GITHUB_ENV
        echo "conda activate nba_env" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        conda activate nba_env
        conda install -c conda-forge mamba -y
        mamba env update --file environment.yml --name nba_env

    - name: Lint with flake8
      run: |
        conda activate nba_env
        conda install flake8 -y
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda activate nba_env
        conda install pytest -y
        pytest
